workflows:
  ios-workflow:
    name: iOS App Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App.xcworkspace"
        XCODE_SCHEME: "App"
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npx cap add ios || true
          npx cap sync ios
          cd ios && pod init && pod install && cd ..
      - name: Build iOS app
        script: |
          xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -sdk iphoneos -configuration Release build CODE_SIGNING_ALLOWED=NO
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/*.ipa
